### ISSUE TITLE
Protocol-less URLs fail

### ISSUE THREAD

**Issue by steverowling** [johndwells/craft.minimee#10]
Hi John

Just trying out Minimee on my latest Craft build and noticed that protocol-less URLs (e.g. //code.jquery.com/jquery-1.11.0.min.js) fail with a malformed URL error.

For this project, I can just revert to normal URLs, but wondered if you had any plans to add support for protocol-less URLs in the future.

Cheers

Steve

**Comment by johndwells** [comment]
Hey Steve - looks like that's being thrown by Guzzle, the underlying library that Minimee uses to fetch remote assets.  We use the version which comes with Craft. I haven't found yet anyone reporting the issue to Guzzle, so I'll do what I can to raise a report.

Just a side note: I always recommend that for CDN-hosted assets like jquery, leave those outside of Minimee, since it's highly likely they're already cached in your visitor's browser...

**Comment by steverowling** [comment]
Fair point about CDN-hosted assets. I'm still at the local dev stage on this site and was just testing out Minimee to get a feel for how it works and how to use when the error popped up.

**Comment by johndwells** [comment]
Hey @steverowling,

I've just released 0.9.5 which should protect against this case when you are cURLing to a protocol-less URL.  Thanks for your patience and input!

Cheers,
John
