### ISSUE TITLE
Cachebusted file does not change when orginal file changes.

### ISSUE THREAD

**Issue by KnutSv** [johndwells/craft.minimee#16]
After creating a cache-folder in my "public_html" folder, Minimee generates cache-files and everything seems to be working. But when I change my original CSS-file and clear the cache new cache-files are not added. If I delete the files in the cache folder new files are added with the new code, but with the same name (so no cache-bust). The strange thing is: while the files in the cache folder now contain the right code, the file that is served to the user does not. I've tested with several browsers and am pretty sure it's not some kind of extreme browser cache issue.

**Comment by johndwells** [comment]
Hi,

I assume you've configured Minimee to use that cache folder that you've created in public_html?

Minimee makes a cache clearing function available in Craft's Settings page only when using Craft's default storage for saving the caches - but once you are writing caches to a public_html folder, that's no longer relevant (and shouldn't be available as an option).

Also, making changes to your CSS should cause Minimee to auto-regenerate the file, so you shouldn't need to manually clear/delete anything.

But you're saying that when you do update your CSS file, Minimee isn't detecting this change?

**Comment by KnutSv** [comment]
Yes, when i upload new css-files (and probably js-files as well) nothing happens to the cached files. When I delete the cached files they are generated with the right code, but with the same name as before (so no cache bust). This is on a nginx-server btw.

This is a series of screenshots highlighting my issue. 
![minimee-issue](https://cloud.githubusercontent.com/assets/821570/7697338/e8189d58-fe06-11e4-9922-f66fb4f1da9b.png)

This is my Minimee settings page:
![minimee-settings](https://cloud.githubusercontent.com/assets/821570/7697394/b806123e-fe07-11e4-8bd9-db915ba604b1.png)

**Comment by johndwells** [comment]
Hi,

Thanks for the screenshots, very helpful!

OK, so the clue was in the "000000000" in each cache filename.  This is supposed to be a timestamp of when the latest change was, so it should be something numerical like 1432024886.  But Minimee only cache's *local* files, and when it tries to cache a *remote* file, it doesn't attempt to check its timestamp, and merely uses the string of zeros.  This is because it would be far too costly to attempt to read the headers of remote files that are fetched over cURL.

Now, I'm sure your assets are not remote - but if you're passing a fully qualified URL to Minimee, it will think it is.  So the answer is to change your template to use local paths to your assets, e.g. "/assets/css/styles.css".

Does that make sense?

Cheers,
John

**Comment by KnutSv** [comment]
Thanks, that did the trick. When I was developing on localhost I had to use absolute URLs because the relative URLs were relative to localhost and not the project folder.

Now it regenerates the files when the originals change and appends the timestamp to the filename. Works like a charm :)

**Comment by johndwells** [comment]
Great! Glad we worked it out, thanks for the thorough screenshots & info to help debug.
