### ISSUE TITLE
Template Error: Variable "minimeeSettings" does not exist

### ISSUE THREAD

**Issue by ademers** [johndwells/craft.minimee#30]
I updated Craft from 2.6.2950 to 2.6.2968 and Minimee from 0.8.1 to 0.9.8. DB. When I checked the front-end, I saw this error:

```
Internal Server Error

array_key_exists() expects parameter 2 to be array, null given
```

I enabled dev mode, and saw the above template error. Screenshot: https://cl.ly/110q012m3R3s

Template code:

```
    {{ craft.minimee.css([
      '/theme/css/xyz.css',
      '/theme/webfonts/ss-social.css',
      '/theme/js/vendor/fancybox/jquery.fancybox.css'
    ], minimeeSettings) }}
    {{ craft.minimee.js([
      '/theme/js/vendor/modernizr-2.7.1.min.js'
    ], minimeeSettings) }}
```

Server info: PHP 5.3.10  & MySQL 5.5.43.

I tested this locally on MAMP with PHP 5.6.10, and did not get this error. 

Thanks for your help!

**Comment by johndwells** [comment]
I Andrea - I've replied to you in Slack but just to be thorough. The `minimeeSettings` is a simple run-of-the-mill Twig variable, so the error being thrown simply states that the variable hasn't been set.  I'm surprised that you'd be encountering an error only now - an older version of Minimee wouldn't have been able to suppress an error like that.

Anyway - if you were intending to pass runtime settings into Minimee's `css()` and `js()` tags, then you'll want to set `minimeeSettings` accordingly; but if that wasn't your intention you can simply remove them, so that your code looks more like this:

    {{ craft.minimee.css([
      '/theme/css/xyz.css',
      '/theme/webfonts/ss-social.css',
      '/theme/js/vendor/fancybox/jquery.fancybox.css'
    ]) }}
    {{ craft.minimee.js([
      '/theme/js/vendor/modernizr-2.7.1.min.js'
    ]) }}

And that should resolve that error.

**Comment by ademers** [comment]
Hi John, the culprit was `minimeeSettings` in an Craft Env conditional. I didn't develop the templates, so had no idea it was there. Thanks again!
